"""
This type stub file was generated by pyright.
"""

crypto_hash_BYTES = ...
crypto_hash_sha256_BYTES = ...
crypto_hash_sha512_BYTES = ...

def crypto_hash(message):
    """
    Hashes and returns the message ``message``.

    :param message: bytes
    :rtype: bytes
    """
    ...

def crypto_hash_sha256(message):
    """
    Hashes and returns the message ``message``.

    :param message: bytes
    :rtype: bytes
    """
    ...

def crypto_hash_sha512(message):
    """
    Hashes and returns the message ``message``.

    :param message: bytes
    :rtype: bytes
    """
    ...
