"""
This type stub file was generated by pyright.
"""

crypto_secretbox_KEYBYTES = ...
crypto_secretbox_NONCEBYTES = ...
crypto_secretbox_ZEROBYTES = ...
crypto_secretbox_BOXZEROBYTES = ...
crypto_secretbox_MACBYTES = ...
crypto_secretbox_MESSAGEBYTES_MAX = ...

def crypto_secretbox(message, nonce, key):
    """
    Encrypts and returns the message ``message`` with the secret ``key`` and
    the nonce ``nonce``.

    :param message: bytes
    :param nonce: bytes
    :param key: bytes
    :rtype: bytes
    """
    ...

def crypto_secretbox_open(ciphertext, nonce, key):
    """
    Decrypt and returns the encrypted message ``ciphertext`` with the secret
    ``key`` and the nonce ``nonce``.

    :param ciphertext: bytes
    :param nonce: bytes
    :param key: bytes
    :rtype: bytes
    """
    ...
